In [1]:
import numpy as np

### 넘파이의 초기값 지정
- np.zeros(갯수)
- np.zeros([행수,열수])
- np.ones(갯수)
- np.ones([행수,열수])
- np.empty(갯수)
np.empty([행수,열수])

In [2]:
# 0으로 초기값 지정 
arr1 = np.zeros(10)
arr2 = np.zeros([2,3])
print(f'1차원 = {arr1}' )
print(f'2차원 = {arr2}' )

1차원 = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2차원 = [[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# 1로 초기값 지정 
arr3 = np.ones(10)
arr4 = np.ones([2,3])
print(f'1차원 = {arr3}' )
print(f'2차원 = {arr4}' )

1차원 = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
2차원 = [[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# empty 초기값 지정 
arr5 = np.empty(10)
arr6 = np.empty([2,3])
print(f'1차원 = {arr5}' )
print(f'2차원 = {arr6}' )

1차원 = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
2차원 = [[1. 1. 1.]
 [1. 1. 1.]]


### 지정한 숫자만큼 값이 증하는 np배열
- np.arange(start,end,step) => 넘파이배열. end-1 까지만 생성
- np.arange(end) => 넘파이배열. 0~ end-1 까지만 생성
- range(start,end,step)와 비슷 => 리스트. end-1 까지만 생성

In [6]:
# range 객체 => 리스트화
print(range(0,10), type(range(0,10)))
print(list(range(0,10)), type(list(range(0,10))) )
print(range(0,10,2))
print(list(range(0,10,2)))

range(0, 10) <class 'range'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>
range(0, 10, 2)
[0, 2, 4, 6, 8]


In [7]:
# np.arange() => 넘파이 배열 
print(np.arange(0,10), type(np.arange(0,10)))
print(np.arange(0,10, 2))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0 2 4 6 8]


In [8]:
print(np.arange(20), type(np.arange(20)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>


### 넘파이구성요소의 자료형
- type(변수/값) => 전체객체의 자료형
- 넘파이배열.dtype : int32, <U2 , float64
- 넘파이배열생성시 자료형함께 지정하기
-    np.array(리스트, dtype=자료형)

In [10]:
arr7 = np.arange(0,100,20)
arr7

array([ 0, 20, 40, 60, 80])

In [11]:
arr7.dtype

dtype('int32')

In [12]:
arr8 = np.array(['사과','수박','포도'])
arr8.dtype

dtype('<U2')

In [13]:
arr9 = np.array([1.1, -8.9, 2.5])
arr9.dtype

dtype('float64')

In [14]:
# 1,2,3 => 문자열로 지정해서 넘파이 배열로 생성 
arr10 = np.array([1,2,3], dtype='<U2')
arr10

array(['1', '2', '3'], dtype='<U2')

In [15]:
# 1,2,3 => 실수형으로 지정해서 넘파이 배열로 생성 
arr11 = np.array([1,2,3], dtype='float64')
arr11

array([1., 2., 3.])

In [16]:
arr11.dtype

dtype('float64')

### 넘파이배열의 캐스팅 - 자료형변환
- 넘파이배열.astype(자료형)
- 자료형은 int32, <U2 , float64

In [17]:
# 정수형 넘파이배열 => 문자열 넘파이배열 
arr12 = np.array([100, 34, 55])
print(f'arr12={arr12}, 데이타형은? {arr12.dtype}')

arr12=[100  34  55], 데이타형은? int32


In [18]:
arr13 = arr12.astype('<U2')
print(f'arr13={arr13}, 데이타형은? {arr13.dtype}')

arr13=['10' '34' '55'], 데이타형은? <U2


### 일반 자료형 변형은? int() / float() / str()
- 퀴즈 : 캐스팅
- 1) 일반자료형 변경 : 숫자(100) => 문자열('100')
- 2) 일반자료형 변경 : 문자열('0') => 실수형숫자(0.)
- 3) 일반자료형 리스트(['사과','포도']) = 문자열(사과/포도) 
- 4) 일반자료형(숫자리스트) => 넘파이배열(문자형넘파이배열) 
-    [1, 100, 4]           => ...
- 5) 넘파이배열(실수형) => 넘파이배열(문자형)

In [20]:
# 1) 일반자료형 변경 : 숫자(100) => 문자열('100')
a = 100
aa = str(a)
print(a, type(a), aa, type(aa))

100 <class 'int'> 100 <class 'str'>


In [21]:
# 2) 일반자료형 변경 : 문자열('0') => 실수형숫자(0.)
b = '0'
bb = float(b)
print(b, type(b), bb, type(bb))

0 <class 'str'> 0.0 <class 'float'>


In [23]:
# 3) 일반자료형 리스트(['사과','포도']) = 문자열(사과/포도) 
c = ['사과','포도']
cc = '/'.join(c)
print(c, type(c), cc, type(cc))

['사과', '포도'] <class 'list'> 사과/포도 <class 'str'>


In [24]:
# 4) 일반자료형(숫자리스트) => 넘파이배열(문자형넘파이배열) 
#     [1, 100, 4]           => ...

d = [1, 100, 4]
dd = np.array(d, dtype='<U2')
print(d, type(d), dd, dd.dtype)

[1, 100, 4] <class 'list'> ['1' '10' '4'] <U2


In [25]:
# 5) 넘파이배열(실수형) => 넘파이배열(문자형) 
e = np.array([5.6, 7.1, -9.0])
ee = e.astype('<U2')
print(e, e.dtype, ee, ee.dtype)

[ 5.6  7.1 -9. ] float64 ['5.' '7.' '-9'] <U2


### 넘파이배열의 구조 변경
- 1차원 => 2차원 / 2차원=>1차원
- 넘파이배열명.reshape(행수,열수) : 1차원=>2차원, 2차원=>2차원
- 넘파이배열명.flatten() : 2차원 => 1차원
- 넘파이배열명.reshape(-1,?) : 전체요소(size)기준. 2차원

In [26]:
#  1차원 => 2차원
npArr1 = np.array([100, 300, 500, 1, 2])
print(f'npArr1={npArr1}, 차원={npArr1.ndim}, 구조={npArr1.shape}')
npArr2 = npArr1.reshape(5,1)
print(f'\n\n npArr2={npArr2}, \n차원={npArr2.ndim}, 구조={npArr2.shape}')

npArr1=[100 300 500   1   2], 차원=1, 구조=(5,)


 npArr2=[[100]
 [300]
 [500]
 [  1]
 [  2]], 
차원=2, 구조=(5, 1)


In [27]:
# 2차원(2행5열) => 2차원(5행2열) 
npArr3 = np.array([['a','b','c','d','e'],['a','b','c','d','e']])
print(f'npArr3={npArr3}, 차원={npArr3.ndim}, 구조={npArr3.shape}')
npArr4 = npArr3.reshape(5,2)
print(f'\n\n npArr4={npArr4}, \n차원={npArr4.ndim}, 구조={npArr4.shape}')

npArr3=[['a' 'b' 'c' 'd' 'e']
 ['a' 'b' 'c' 'd' 'e']], 차원=2, 구조=(2, 5)


 npArr4=[['a' 'b']
 ['c' 'd']
 ['e' 'a']
 ['b' 'c']
 ['d' 'e']], 
차원=2, 구조=(5, 2)


In [28]:
# 2차원(2행5열) => 2차원(1행10열) 
# 2차원(2행5열) => 1차원(10) : 배열명.flatten()
npArr5 = np.array([['a','b','c','d','e'],['a','b','c','d','e']])
print(f'npArr5={npArr5}, 차원={npArr5.ndim}, 구조={npArr5.shape}')
npArr6 = npArr5.reshape(1,10)
print(f'\n\n npArr6={npArr6}, \n차원={npArr6.ndim}, 구조={npArr6.shape}')
npArr7 = npArr5.flatten()
print(f'\n\n npArr7={npArr7}, \n차원={npArr7.ndim}, 구조={npArr7.shape}')

npArr5=[['a' 'b' 'c' 'd' 'e']
 ['a' 'b' 'c' 'd' 'e']], 차원=2, 구조=(2, 5)


 npArr6=[['a' 'b' 'c' 'd' 'e' 'a' 'b' 'c' 'd' 'e']], 
차원=2, 구조=(1, 10)


 npArr7=['a' 'b' 'c' 'd' 'e' 'a' 'b' 'c' 'd' 'e'], 
차원=1, 구조=(10,)


### 넘파이배열명.reshape(-1,컬럼갯수) : 전체요소(size)기준. 2차원

In [29]:
npArr8=np.array([30, 80, 100, 79, 80, 100])
print(f'\n\n npArr8={npArr8}, \n차원={npArr8.ndim},\
      \n구조={npArr8.shape},  \n총갯수={npArr8.size}')



 npArr8=[ 30  80 100  79  80 100], 
차원=1,      
구조=(6,),  
총갯수=6


In [30]:
# 1행6열 =>  ?행2열
npArr9=npArr8.reshape(-1,2)
print(f'\n\n npArr9={npArr9}, \n차원={npArr9.ndim},\
      \n구조={npArr9.shape},  \n총갯수={npArr9.size}')



 npArr9=[[ 30  80]
 [100  79]
 [ 80 100]], 
차원=2,      
구조=(3, 2),  
총갯수=6


In [31]:
# 1행6열 =>  ?행3열
npArr10=npArr8.reshape(-1,3)
print(f'\n\n npArr10={npArr10}, \n차원={npArr10.ndim},\
      \n구조={npArr10.shape},  \n총갯수={npArr10.size}')



 npArr10=[[ 30  80 100]
 [ 79  80 100]], 
차원=2,      
구조=(2, 3),  
총갯수=6
