# numpy04

- 일반 난수
- 넘파이 난수 배열

In [1]:
import numpy as np

## 일반난수
- 내장모듈 임포트 import random
- random.random() : 0 ~ 1 난수
- random.randint()
- random.randomrange()
- random.randomchoice()

In [2]:
import random

In [17]:
print(random.random())
print(random.random())

0.8621660401484215
0.21080050330776412


In [92]:
# 1~10 정수
print(random.randint(1,10))
print(random.randint(1,10))

10
2


In [87]:
# !~100 홀수
print(random.randrange(1,100,2)) 
print(random.randrange(1,100,2))

1
27
48


In [106]:
# 0~100 짝수
print(random.randrange(0,100,2)) 
print(random.randrange(0,100,2)) 

54
90


In [117]:
# 범위를 지정해서 난수 실수 발생
print(random.uniform(1,10))
print(random.uniform(1,10))

7.343013330148839
1.766303758255734


## 리스트에서 임의의 인덱스 뽑기 => 리스트 난수
- 내장모듈 임포트 import random
- random.choice(리스트변수나 리스트) : 1개 출력
- random.sample(리스트변수나 리스트, n) : n 만큼 출력

In [118]:
fruitList = ['사과','수박','배','체리','자두','멜론','귤']
fruitList

['사과', '수박', '배', '체리', '자두', '멜론', '귤']

In [123]:
print(random.choice(fruitList))
print(random.choice(fruitList))

멜론
멜론


In [127]:
print(random.sample(fruitList, 5))

['수박', '귤', '배', '체리', '사과']


# 넘파이배열의 난수
- 외장 모듈 임포트 import numpy as np

## 실수(0~1)
- 외장모듈 임포트 import numpy as np
- np.random.rand(갯수) : 갯수만큼 생성되는 넘파이 배열 => 실수
- np.random.randn(갯수) : 갯수만큼 생성되는 넘파이 배열 => 실수
- np.random.rand(행수,열수) : n차원 넘파이 배열 => 실수
- np.random.randn(행수,열수) : n차원 넘파이 배열 => 실수

## 양의 정수(0~)
- np.random.randint(start,end,size=갯수)
- np.random.randint(srart,end,size=(행수,열수))

## 음의 정수(0~)
- np.random.randint(start,end,size=갯수)
- np.random.randint(srart,end,size=(행수,열수))

## 숫자중에서 갯수만큼 뽑는다. (중복가능/중복불가능)
- np.random.choice(숫자, size=갯수, replace=True/False) 

## 리스트에서 개수만큼 뽑는다. (중복가능/중복불가능)
- np.random.choice(리스트, size=개수, replace=True/False)

## 확률을 지정해서 숫자중에서 뽑는다.
- np.random.choice(숫자, 개수, p=확률배열)

## 넘파이배열의 순서를 섞는다.
- np.random.shuffle(리스트/튜플/넘파이배열...)

In [128]:
np.random.rand(3)

array([0.37382193, 0.23482609, 0.17496038])

In [129]:
np.random.rand(5)

array([0.93592724, 0.66115142, 0.67460703, 0.69656586, 0.90536923])

In [130]:
np.random.rand(2,3)

array([[0.53850728, 0.48282553, 0.68068591],
       [0.5025693 , 0.25738196, 0.48004441]])

In [131]:
np.random.randint(100)

52

In [132]:
np.random.randint(100,200,size=5)

array([110, 165, 134, 134, 142])

In [133]:
np.random.randint(100,200,size=(2,2))

array([[170, 187],
       [141, 170]])

In [134]:
np.random.randint(-20,-10,size=5)

array([-13, -20, -19, -12, -11])

In [135]:
np.random.randint(-100,-10,size=(3,3))

array([[-14, -28, -99],
       [-90, -11, -40],
       [-14, -49, -53]])

In [136]:
# 0~9까지에서 3개뽑기, 중복허용
np.random.choice(10, size=3, replace=True)

array([2, 2, 6])

In [137]:
# 0~9까지에서 3개뽑기, 중복 불가능
np.random.choice([0,1,2,3,4,5,6,7,8,9], size=3, replace=False)

array([9, 7, 3])

In [144]:
# 리스트에서 개수 정해뽑기
np.random.choice(['꽝','스타벅스10만원권','디지털피아노','이마트상품권 20만원권'], size=2, replace=False)

array(['꽝', '디지털피아노'], dtype='<U12')

In [159]:
# 확률을 지정해서 랜덤 뽑기
# 확률 배율 합계는 1
plist =['꽝','스타벅스10만원권','디지털피아노','이마트상품권 20만원권','베스킨라빈스 파인트', '범블비']
np.random.choice(plist, 1, p=[0.5, 0.1,0.1,0.1,0.1,0.1 ]) # 각각의 확률

array(['디지털피아노'], dtype='<U12')

In [168]:
# 구성요소의 순서를 섞는다. => 원본집합형자료(리스트, numpy배열)의 순서가 변경된다.
result1 = [10,20,30,40,50]
np.random.shuffle(result1)
result1

[40, 30, 50, 10, 20]

In [180]:
result2 = np.array([100,200,300,400])
np.random.shuffle(result2)
result2

array([200, 100, 400, 300])

In [186]:
# 문자열도 셔플 된다
result3 = np.array(['100','200','300','400'])
np.random.shuffle(result3)
result3

array(['100', '300', '200', '400'], dtype='<U3')

## np.seed()
- 난수 기억
- 순서
```
np.seed(숫자) # 시드 설정 = 난수 발생 1
난수발생1
난수발생 2
np.seed(숫자) # 설정된 시드의 난수
난수 발생1
```

In [249]:
print(np.random.rand())
print(np.random.rand())

0.8691851258630294
0.852735345752473


In [282]:
# 10으로 seed 지정 
np.random.seed(10)
print(np.random.rand())
print(np.random.rand())

0.771320643266746
0.0207519493594015


In [289]:
np.random.seed(10)
print(np.random.rand())

0.771320643266746
