# Numpy05

## 넘파이 수학함수  
    - 조건 : 넘파이 배열형태의 숫자 자료형만 가능(문자형 사용 불가)
   
   ### 두 넘파이 배열에서 큰수나 작은수 출력
    - np.maximum(배열1, 배열2)
    - np.minimum(배열1, 배열2)
    
   ### 같은 배열에서 큰수나 작은수 출력( 최댓값, 최솟값)
    - np.max(배열) => 결과 하나
    - np.min(배열) => 결과 하나
    - np.max(배열, axis = 0 ) => 컬럼의 최댓값 (결과 컬럼수)
    - np.min(배열, axis = 1 ) => 행의 최댓값 (결과 행수)
    
   ### 같은 배열에서 합과 평균
    - np.sum(배열) => 결과 하나
    - np.mean(배열) => 결과 하나
    - np.sum(배열, axis=0/1) = 배열이름.sum(axis=0/1) axis가 0일때 -> 컬럼기준/ axis가 1일때 -> 행기준
    - np.mean(배열, axis=0/1)= 배열이름.mean(axis=0/1) 
 
## 병합
   
   ### 기존 배열을 이용해서 새로운 배열 만들기
    - np.vstack((배열1,배열2)) : 행으로 합치기
    - np.hstack((배열1,배열2)) : 열로 합치기
    - np.concatenate((배열1,배열2, axis=1/0)) : 행/열로 합치기(이건 2차원배열로 해야 오류가 없단다..)
    
   

In [2]:
import numpy as np

In [19]:
# 넘파이 배열 생성 및 minimum/maximum
npArr1 = np.array([1,2,3,4,5])
npArr1
npArr2 = np.arange(5,10)
npArr2
np.minimum(npArr1,npArr2)
np.maximum(npArr1,npArr2)
# npArr3 = np.array(['가','나','다'])
# npArr4 = np.array(['마','바','사'])
# np.minimum(npArr3,npArr4)
# np.maximum(npArr3,npArr4)  => 오류남

array([5, 6, 7, 8, 9])

In [44]:
# max/min
npArr5 = np.arange(1,20)
np.max(npArr1) # 최대값
np.min(npArr1) # 최소값

# 2차원 배열
npArr6 = np.arange(20)
npArr7 = npArr6.reshape(4,5)
print(npArr7)
print('컬럼의 최댓값',np.max(npArr7, axis = 0))
print('행의 최솟값',np.min(npArr7, axis = 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
컬럼의 최댓값 [15 16 17 18 19]
행의 최솟값 [ 0  5 10 15]


In [50]:
print('1차원 npArr5의 합',np.sum(npArr5))
print('1차원 npArr5의 평균',np.mean(npArr5))
print('2차원 npArr7의 합',np.sum(npArr7, axis=0))
print('2차원 npArr7의 평균',np.mean(npArr7, axis=0))

1차원 npArr5의 합 190
1차원 npArr5의 평균 10.0
2차원 npArr7의 합 [30 34 38 42 46]
2차원 npArr7의 평균 [ 7.5  8.5  9.5 10.5 11.5]


In [67]:
npArr8 = np.array([15,10,67,80])
npArr9 = np.array([33,56,78,77])
print(np.vstack((npArr8,npArr9))) 
print(np.hstack((npArr8,npArr9)))
npArr10 = np.array([[15,10,67,80]])
npArr11 = np.array([[33,56,78,77]])
print(np.concatenate((npArr10,npArr11),axis=1))
print(np.concatenate((npArr10,npArr11),axis=0))

[[15 10 67 80]
 [33 56 78 77]]
[15 10 67 80 33 56 78 77]
[[15 10 67 80 33 56 78 77]]
[[15 10 67 80]
 [33 56 78 77]]
