# Numpy06
- 정렬
- 중복값 제거
- 단위행열
- All& Any
- Boolean Index


In [2]:
import numpy as np

## 배열의 정렬
- np.sort(배열1차) / 배열명.sort() : 오름차순
- np.sort(배열1차)[::-1] : 내림차순
- np.sort(배열2차, axis=0/1)

In [5]:
arr1 = np.random.randn(10)
print(arr1)
np.sort(arr1) # 정렬화 
print(arr1)
np.sort(arr1)[::-1]

[ 1.00251736  0.70185659  1.39852449  0.35965014  0.06968815 -0.01915922
 -0.13994869  0.07420553 -1.9326974   0.85473764]
[ 1.00251736  0.70185659  1.39852449  0.35965014  0.06968815 -0.01915922
 -0.13994869  0.07420553 -1.9326974   0.85473764]


array([ 1.39852449,  1.00251736,  0.85473764,  0.70185659,  0.35965014,
        0.07420553,  0.06968815, -0.01915922, -0.13994869, -1.9326974 ])

In [ ]:
# 2차원 넘파이 배열 
arr2 = np.random.randn(10)
arr2 = arr2.reshape(5,2)
print(arr2)

# 컬럼단위로 정렬 
np.sort(arr2, axis=0)
print(np.sort(arr2, axis=0))
np.sort(arr2, axis=0)[::-1]
print(np.sort(arr2, axis=0)[::-1])

# 행단위로 정렬 
np.sort(arr2, axis=1)
print(np.sort(arr2, axis=1))

## 중복값 제거
- np.unique(배열명)

In [7]:
npNameArr =np.array( ['순희', '영희', '철수',
             '순희','영희', '영희' ])
print(npNameArr)
np.unique(npNameArr)

['순희' '영희' '철수' '순희' '영희' '영희']


array(['순희', '영희', '철수'], dtype='<U2')

## 단위행열
- 대각선의 원소가 1, 나머지는 모두 0
- np.identity(1의갯수=대각선수) => float64
- np.identity(n=1의갯수, dtype=int) => int

In [12]:
npIden1 = np.identity(5)
npIden1.dtype
print(npIden1.dtype)
print(npIden1)
print("------------------")
npIden2 = np.identity(n=4, dtype=int)
npIden2.dtype
print(npIden2.dtype)
print(npIden2)

float64
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
------------------
int32
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## 조건에 따라 True/False

###  조건식/all/any
- 넘파이배열을 이용한 조건식 => True/False 배열수만큼 리턴
- all(조건식) => 모든 값이 조건식에 만족 => True (And)
- any(조건식) => 값 중 하나만 만족 => True (Or)

### 비교연산
- 넘파이 배열간의 갯수(size)가 같아야한다.
- 배열1 비교연산자 배열2  
, <, ==

- 배열 각각의 요소 비교

### np.where()
- np.where(조건식, True, False)

In [23]:
arr1 = np.arange(1,11)
print(arr1,'\n')

# 조건식 적용 
arr1>5
print(arr1>5,'\n')
np.any(arr1>5) 
print(np.any(arr1>5),'\n')
print(np.any(arr1<0),'\n')
print(np.all(arr1>5),'\n')
print(np.all(arr1>0),'\n')

arrA = np.array([1, 10, 5])
arrB = np.array([5, 10, 1])
print(arrA > arrB,'\n')
print(arrA < arrB,'\n')
print(arrA == arrB,'\n')
print(arrA,'\n')
print(arrA > 9,'\n')
print(np.where(arrA>9, True, False),'\n')
np.where(arrA>9, '참이다', '거짓이다')

[ 1  2  3  4  5  6  7  8  9 10] 

[False False False False False  True  True  True  True  True] 

True 

False 

False 

True 

[False False  True] 

[ True False False] 

[False  True False] 

[ 1 10  5] 

[False  True False] 

[False  True False] 



array(['거짓이다', '참이다', '거짓이다'], dtype='<U4')

In [29]:
##### a 값이 0이면 0, 그렇지 않다면 곱하기 2
arrC = np.array([0, 10, 5, 0])
print(arrC)
np.where(arrC==0, '0이다', arrC*2)

[ 0 10  5  0]


array(['0이다', '20', '10', '0이다'], dtype='<U11')

In [32]:
result1 = np.where(arrC==0, 0, arrC*2)
print(result1)

result1.dtype

[ 0 20 10  0]


dtype('int32')

### 배열안에 Null 값 표시
- 넘파이배열에서 Null 값은? np.NaN
- np.isnan(배열명)
- Null 값이면 True 아니면 False

In [36]:
arrD = np.array([np.NaN, 5, np.NaN, 0, -1])
print(arrD)
np.isnan(arrD)

[nan  5. nan  0. -1.]


array([ True, False,  True, False, False])

### 넘파이배열의 Boolean Indexing

- 넘파이배열에서 조건식에 맞는 값만 추출할 때 이용 
- True/False 
- 넘파이배열명[조건식]

In [38]:
# size=7 (중복값)
fruitArr = np.array(['사과','배','배',
                     '사과','사과', '귤', '수박'])
print(fruitArr)

# 조건식 == 값 스타일로 적용 
fruitArr == '사과'

['사과' '배' '배' '사과' '사과' '귤' '수박']


array([ True, False, False,  True,  True, False, False])

In [41]:
# 난수값을 이용하여 배열 생성 
numArr = np.random.randn(7,5)
print(numArr)
print()
# numArr 넘파이배열에 
# (fruitArr == '사과') 불링인덱싱 적용하기 
result2 = numArr[fruitArr == '사과']
print(numArr)
print()
# fruitArr == '사과' True 인 인덱싱이 행으로 적용
# result2 1/4/5 행만 표시 
print(result2)
print()
result3 = numArr[fruitArr == '수박']
print(result3)

[[ 2.23974284 -1.14151049 -1.62810648  1.89276671 -0.06989205]
 [ 0.0383742   0.26469096 -1.72388456  0.58391584  1.59642772]
 [ 0.52389408  0.7533661  -0.27842711  1.14277774 -0.13901497]
 [ 1.79118713  0.60351713 -1.28039346  2.19780179 -0.33275057]
 [-0.83262112 -1.57283562  1.28352123 -0.15058501  1.54513616]
 [ 1.23829016 -0.04946257 -2.35439194 -0.5012854   1.41352098]
 [-1.34801559  0.57961141  0.02549893  0.46789331  0.64922931]]

[[ 2.23974284 -1.14151049 -1.62810648  1.89276671 -0.06989205]
 [ 0.0383742   0.26469096 -1.72388456  0.58391584  1.59642772]
 [ 0.52389408  0.7533661  -0.27842711  1.14277774 -0.13901497]
 [ 1.79118713  0.60351713 -1.28039346  2.19780179 -0.33275057]
 [-0.83262112 -1.57283562  1.28352123 -0.15058501  1.54513616]
 [ 1.23829016 -0.04946257 -2.35439194 -0.5012854   1.41352098]
 [-1.34801559  0.57961141  0.02549893  0.46789331  0.64922931]]

[[ 2.23974284 -1.14151049 -1.62810648  1.89276671 -0.06989205]
 [ 1.79118713  0.60351713 -1.28039346  2.19780179 -

## 조건식이 참인 값의 갯수 구하기
- np.sum(배열명)
- (조건식).sum()

In [44]:
# 10개 난수정수
arrE = np.random.randint(1,11,10)
print(arrE )
print()

# 배열의 총합 
np.sum(arrE)
print(np.sum(arrE))
print()

# 조건식 적용 
arrE>7
print(arrE>7)
print()

# 조건식에 만족하는 총 합?
(arrE>7).sum()

[ 6  3  7 10  6  1  7 10  3  8]

61

[False False False  True False False False  True False  True]



3

## 퀴즈  
    1) 50개의 정수난수로 된 넘파이 배열 생성 
    2) 역순 소팅 (가장 큰값이 가장 먼저나온다) 
    3) 전체길이를 구한 후 상위 5%에 해당하는 값만 표시

In [46]:
# 1) 50개의 정수난수로 된 넘파이 배열 생성 (0~100사이 숫자)
matrix_50 = np.random.randint(0,101,50)
print(matrix_50)
print(len(matrix_50))
print(len(np.unique(matrix_50)))

[ 31  50   5  98  75  66  77  88 100  80   8  79   9  78  55  70  72  11
  75  95  28   4  61  81  29  40  31  52   7  30  23  69  65  22   1   5
  43  23  11  85   2  34  85  23  16   9  77  78  16  69]
50
38


In [47]:
matrix_50 = np.random.choice(101, size=50, replace=False)
print(matrix_50)
print(len(np.unique(matrix_50)))
print(len(np.unique(matrix_50)))

[  2  87  84  78  92  25  41  39  62  58  24  56  77  95  83  47  35  14
  46  10  72  63  20  15  71  40  16  91  57  75  32  51  18  86   9   1
  68  81  53  12  80  66  82  54  22  59  79  98 100  31]
50
50


In [48]:
# 2) 역순 소팅 (가장 큰값이 가장 먼저나온다) 
matrix_50 = np.sort(matrix_50)[::-1]
matrix_50

array([100,  98,  95,  92,  91,  87,  86,  84,  83,  82,  81,  80,  79,
        78,  77,  75,  72,  71,  68,  66,  63,  62,  59,  58,  57,  56,
        54,  53,  51,  47,  46,  41,  40,  39,  35,  32,  31,  25,  24,
        22,  20,  18,  16,  15,  14,  12,  10,   9,   2,   1])

In [50]:
# 3) 상위 5%에 해당하는 값만 표시 
n = int(0.05*len(matrix_50))
print(n)
matrix_50[0:n]

2


array([100,  98])

## 외부파일 불러오기
    배열명변수 = np.loadtxt('파일경로', 
                        delimiter='구분자',
                        dtype=데이타형)
    http://naver.me/5yraKmr1
    0122
    data/ratings.dat 다운로드후 작업폴더안에 data 폴더에 준비

In [59]:
data = np.loadtxt('data/ratings.dat', 
                  delimiter='::', 
                  dtype=np.int32)

In [60]:
# 5개만 표시하기 
data[:5]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]])

In [61]:
data.shape

(1000209, 4)

In [62]:
# 총 데이타갯수
data.size

4000836

In [63]:
# 3컬럼만 데이타 표시 
data[:, 2]

array([5, 3, 3, ..., 5, 4, 4])

In [64]:
# 평점의 평균 (3번컬럼)
result = np.mean(data[:, 2])
result 

3.581564453029317

In [65]:
data[:, 2].mean()

3.581564453029317

### 파일로 저장하기
``` np.savetxt('파일경로', '데이터 변수명')
```


In [ ]:
data2 = np.loadtxt('data/ratings.dat', 
                  delimiter='::', 
                  dtype=np.int32)

In [2]:
# 현재 작업폴더 경로 확인
import os
os.getcwd()

'C:\\dataScience\\day2'

In [3]:
import numpy as np
data = np.loadtxt('data/ratings.dat', delimiter='::',dtype=np.int32)

#### 데이터 형태
```
ratings.dat =>  무비렌즈의 영화평점 데이터
( userid / movieid / ratings / timstamp )
```

In [5]:
print(data.shape)

# 데이터 크키
print(data.size)

(1000209, 4)
4000836


In [6]:
result = np.mean(data[:,2])
result

3.581564453029317

In [ ]:
# 순서대로 50개만 가져와서 .txt파일로 저장하기
result = data[:50]
np.savetxt('data/resultRatings.txt',
           result,
           delimiter=',',
           fmt = '%.3f')

In [ ]:
# .csv 형태로 저장하기!
# fmt 는 format, delimiter는 구분자
np.savetxt('data/resultRatings.csv',
           result,
           fmt='%.3f',
           delimiter=',')